# Generated by Django 5.2.1 on 2025-05-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_perfil_email_perfil_nombre_perfil_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
    ]
