# Generated by Django 5.2.1 on 2025-05-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_responsable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responsable',
        ),
    ]
