# Generated by Django 5.2 on 2025-05-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_producto_area_producto_aula_producto_edificio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
